### ISSUE TITLE
Another possible question and answer

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-community/elm-faq#1]
question (often asked, last time this morning): https://groups.google.com/d/msg/elm-discuss/h-WAC3kgrOU/LtXhQgVNAwAJ

answer (mine, but there are also others out there): https://groups.google.com/forum/#!msg/elm-discuss/h-WAC3kgrOU/ybYtOwq_CgAJ

**Comment by fredcy** [comment]
This is definitely a FAQ. I've thought about addressing it but have not been happy with the solutions so far. Using `foldp'` prevents using StartApp, of course. I think I'll add your solution for now anyway.

**Comment by fredcy** [comment]
I have added an item about `foldp'`.  https://github.com/elm-community/elm-faq/commit/d0d65cadde408e328c06fc227eb3f9331fa05141

**Comment by jvoigtlaender** [comment]
Perfect!
