### ISSUE TITLE
Anchor link to question

### ISSUE THREAD

**Issue by ghost** [elm-community/elm-faq#32]
Using the search, "record" didn't find http://faq.elm-community.org/#how-can-i-change-the-value-of-a-nested-field. Then I wanted to link to that question but couldn't because the question (its heading) doesn't have an anchor link, ala 
![screenshot 2016-10-05 11 23 12](https://cloud.githubusercontent.com/assets/8081877/19109749/aeac06ec-8aee-11e6-9122-bc0f896e1426.png)

**Comment by fredcy** [comment]
The string "record" does not appear anywhere in the item you mention, so of course the search did not find it. Are you asking to modify the text of that item to include "record" somewhere?

The page is generated via Jekyll and I have not found a way to cause Jekyll to generate anchor links on hover the way you suggest. I'll look into that. Any leads?

**Comment by fredcy** [comment]
Note to self: http://bryanbraun.github.io/anchorjs/

**Comment by fredcy** [comment]
I have added anchor links to the FAQ items as requested.

**Comment by ghost** [comment]
Thanks Fred. By the way, what thoughts have you had about doing the site in Elm? For instance, I would have been readier to contribute code for this issue.

**Comment by fredcy** [comment]
It started as a simple Jekyll site at Github Pages. I later added a small Elm app to it that manages the TOC links on each page. I'm open to suggestion as to how it could be made into a full-blown Elm app.
