### ISSUE TITLE
"union type" -> "custom type"

### ISSUE THREAD

**Issue by ashishsc** [elm-community/elm-faq#48]
The FAQ could use an update as the terminology has changed : https://github.com/elm-community/elm-faq/blob/797cb78f68e259b65f1e099dca3eb2cc526919b1/index.md#why-are-things-called-union-types-rather-than-algebraic-data-types

**Comment by fredcy** [comment]
I removed the section on "union type". It did not make sense to just replace "union type" with "custom type" in the FAQ as the section was quite specific to "union type" being the appropriate name.

If someone cares to write up a justification for "custom type" I'd be glad to add it.
