### ISSUE TITLE
Removed functionality still mentioned

### ISSUE THREAD

**Issue by mainlymortal** [elm-community/elm-faq#53]
I'm brand new to the elm community so I'm not sure what the policy is on removing out of date FAQs but somehow I've just come across the section [What does (,) mean?](http://faq.elm-community.org/#what-does--mean-1) which I've discovered is no longer relevant to 0.19.0.

I see the document is supposed to reflect the current version so do you want me to send a pull request removing this part? Just to be clear it needs to be removed because the (,) operator has been removed.

**Comment by fredcy** [comment]
Thanks. Pull requests to fix such issues are always welcome. I went ahead and removed the item about `(,)`, as well as the similar item about `=>`.
