### ISSUE TITLE
Faq recommends innerHtml 

### ISSUE THREAD

**Issue by harrysarson** [elm-community/elm-faq#55]
See: https://github.com/elm-community/elm-faq/blob/gh-pages/index.md#how-can-i-output-literal-html-and-avoid-escaping-of-entities.

This no longer works in elm 19!

**Comment by fredcy** [comment]
Is there an alternative solution, or should we just remove that section?

**Comment by harrysarson** [comment]
There are alternative solutions (e.g. html custom elements) but using them is far more involved than setting `innerHtml` was and possibly out of scope for an faq.

**Comment by fredcy** [comment]
OK, I removed the obsolete content from that item and instead linked to https://github.com/elm/html/issues/172 .

**Comment by fredcy** [comment]
Thanks for reporting the issue.

**Comment by harrysarson** [comment]
My pleasure 😄
