### ISSUE TITLE
FAQ states elm repl doesn't support type annotations but 0.19.1 does

### ISSUE THREAD

**Issue by dlukes** [elm-community/elm-faq#59]
The FAQ says that "elm repl does not support type annotations at all." But in 0.19.1, they seem to work perfectly fine -- e.g. this is a transcript of a session:

```elm
> x : Int
| x = 3
|   
3 : Int
```

So the corresponding FAQ entry can probably be removed now?

**Comment by fredcy** [comment]
OK, I removed that entry. Thanks.
