### ISSUE TITLE
Missing certificate

### ISSUE THREAD

**Issue by David-Klemenc** [elm-community/elm-faq#63]
Browsers report the site as not secure. (other elm sites are using letsencrypt)

**Comment by fredcy** [comment]
Perhaps it's just a matter of accessing it as https://faq.elm-community.org/ ?

**Comment by David-Klemenc** [comment]
Oh I'm so used to getting redirected that writing https did not occur to me ...

**Comment by fredcy** [comment]
The documentation link in this repo had the http link until an hour ago when I corrected it. 

The page is hosted via github pages and I have no idea if an automatic redirect from http to https is possible there.

**Comment by David-Klemenc** [comment]
@fredcy  should be just a setting click: [Enforcing HTTPS for your GitHub Pages site](https://docs.github.com/en/github/working-with-github-pages/securing-your-github-pages-site-with-https#enforcing-https-for-your-github-pages-site)

P.S. the link in the README is http

**Comment by fredcy** [comment]
> @fredcy should be just a setting click: [Enforcing HTTPS for your GitHub Pages site](https://docs.github.com/en/github/working-with-github-pages/securing-your-github-pages-site-with-https#enforcing-https-for-your-github-pages-site)
> 
> P.S. the link in the README is http

Thank you for that. I have just enabled that "enforcing HTTPS" setting, and I updated the README
